### ISSUE TITLE
MonkeyType produces no traces for most of the libs I encounter

### ISSUE THREAD

**Issue by KOLANICH** [Instagram/MonkeyType#103]
for example https://github.com/KOLANICH/NoSuspend.py

**Comment by carljm** [comment]
This isn't actionable without specific repro steps. What specific commands do you run, in what order? What result do you expect? What do you get?

We can reopen if you can provide that information.

**Comment by carljm** [comment]
See the documentation at https://monkeytype.readthedocs.io/en/stable/tracing.html#monkeytype-run

> Because of the way Python treats scripts and imported modules differently, MonkeyType will not record traces for the entry point itself (that is, the script passed to monkeytype run or the module passed to run -m); traces are recorded only for imported modules. If you want to annotate the entry point script/module, write another short script that imports and calls its function(s), and run that script with monkeytype run.
