### ISSUE TITLE
monkeytype expands existing aliases

### ISSUE THREAD

**Issue by carljm** [Instagram/MonkeyType#11]
The stubs generated by monkeytype don't preserve annotations that use type aliases. For example, if a function has the following signature:

```
Number = Union[int, float]

def sum(a: Number, b: Number) -> Number:
    return a + b
```

MonkeyType will expand Number. The generated stub will be:

```
def sum(a: Union[int, float], b: Union[int, float]) -> Union[int, float]: ...
```

Attempting to apply a stub like this will fail with an error from retype of the form `incompatible annotation for ...`.

I'm not sure if there is anything we can do about this. One work around would be an option to omit functions that already have annotation from the generated stubs.

**Comment by ahussain3** [comment]
I noticed a similar problem:
```
ERROR: Failed applying stub with retype:
incompatible existing annotation for {arg.arg!r}. Expected: 'AirtimeTransfer', actual: 'ts.AirtimeTransfer'
```
it would be great if there was an option to recommend that functions with existing type annotations are left alone
