### ISSUE TITLE
monkeytype doesn't extract types from jira library

### ISSUE THREAD

**Issue by rominf** [Instagram/MonkeyType#112]
I have `jira_type_hints_extractor.py`, which uses `jira` library (https://jira.readthedocs.io). I run it with `monkeytype run`, but the sqlite database is empty.

Here is the code:
```
import jira

server = 'https://jira.example.com/'
auth = ('user', 'password')

JIRA = jira.JIRA(server=server, basic_auth=auth)
projects = JIRA.projects()
```

**Comment by carljm** [comment]
This looks like expected [and documented](https://monkeytype.readthedocs.io/en/stable/tracing.html#deciding-which-calls-to-trace) behavior, assuming you've installed the jira library as a third-party library using pip or similar. If your goal is to trace calls within the `jira` library, you could use `MONKEYTYPE_TRACE_MODULES=jira`.

**Comment by rominf** [comment]
Thanks. Sorry for wrong report.
