### ISSUE TITLE
MonkeyType doesn't generate stub files for aiojira

### ISSUE THREAD

**Issue by rominf** [Instagram/MonkeyType#121]
**Steps to reproduce**
Install `aiojira`:
```
$ pip install aiojira
```

Create a file `aiojira_stub_generator.py` with content:
```python
import aiojira

aiojira.Project('', {}, {})
```

Run `monkeytype`:
```
$ export MONKEYTYPE_TRACE_MODULES=aiojira
$ monkeytype run aiojira_stub_generator.py
```

Check `monkeytype.sqlite3` and observe an empty database.

I've reproduced this on 2 different computers.

**Comment by carljm** [comment]
Sorry for the slow response here. I've attempted to repro this, but when I `pip install aiojira` in a Python 3.6 virtualenv, I get these results:

```
>>> import aiojira
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/carljm/.venvs/mtaiojira/lib/python3.6/site-packages/aiojira/__init__.py", line 10, in <module>
    aiojira = aioify(obj=jira, name=__name__, skip=['Issue', 'Project'])
TypeError: aioify() got an unexpected keyword argument 'skip'
```

Any guidance on how to bypass this problem?

**Comment by rominf** [comment]
@carljm, thank you for your response. Sorry for a problem. I updated the readme, before installing the `aiojira` you have to install `aioify` from GitHub tarball (because the new version is not published on PyPI yet).

**Comment by rominf** [comment]
@carljm, BTW I figured out why MonkeyType doesn't generate stub files to `aiojira`. The reason is that all function calls of `aiojira` are in fact wrapper calls from `aioify`. I have to run this:
```shell
$ export MONKEYTYPE_TRACE_MODULES=aioify
```

I will try this later and reopen this if the problem persists.
