### ISSUE TITLE
Generate '...' instead of default value

### ISSUE THREAD

**Issue by wcooley** [Instagram/MonkeyType#123]
From what I can see in [typeshed](https://github.com/python/typeshed/blob/master/stdlib/3/builtins.pyi#L310) and the [mypy docs](https://mypy.readthedocs.io/en/latest/stubs.html#stub-file-syntax), default values for callables' parameters should be replaced with `...`.

This would also obviate the need for '--(in|ex)clude-unparsable-defaults', assuming you could then replace the `object` type with `Any` in the stub output.

**Comment by carljm** [comment]
Yeah, great suggestion, thanks! Dunno how we missed this.

**Comment by carljm** [comment]
Fixed with merge of #128
