### ISSUE TITLE
class attribute types

### ISSUE THREAD

**Issue by deep-fried-bacon** [Instagram/MonkeyType#131]
Hey I was wondering, how hard would it be to create type annotations for class attributes?

**Comment by carljm** [comment]
Pretty hard, unfortunately. MonkeyType works by tracing function calls and recording types. There’s no hook point for tracing assignment to a class attribute (without doing something much more invasive and dangerous like trying to replace class attributes with descriptors at runtime).

**Comment by deep-fried-bacon** [comment]
okay, thanks

**Comment by appukuttan-shailesh** [comment]
@carljm : Apologies for commenting on a closed issue... I was curious why it isn't possible/advisable to read the source code (line by line) to identify assignment to class and instance attributes, and update these with the `type` of the value being assigned.

Something like:
```
class Sample:
    var1 = 10.0
```
being converted to:
```
class Sample:
    var1: float = 10.0
```

I was tempted to write a script that attempts this, but I get the feeling there are obvious pitfalls and why it hasn't been incorporated in MonkeyType.
