### ISSUE TITLE
Don't move existing type-comments to annotations?

### ISSUE THREAD

**Issue by jimbo1qaz** [Instagram/MonkeyType#132]
Is it possible to stop monkeytype from turning existing `# type:` comments into annotations?

I place `np.ndarray[float]` in type comments, since I'm not sure whether it's valid Python syntax, or raises TypeError when placed in annotations. 

(It may/not be MyPy compatible but semi-works with Pycharm.)

**Comment by carljm** [comment]
MonkeyType really just generates stubs, the application of stubs to code is entirely handled by https://github.com/ambv/retype, so retype would need to gain that option before MonkeyType could.

Re your specific issue, you can also put the annotation in quotes as a string (but still as a real annotation, not a comment), and mypy will treat that the same as your comment annotation, and it won't cause any runtime problem. And retype won't mess with it.
