### ISSUE TITLE
Option to run "monkeytype apply" without any stubs or traces

### ISSUE THREAD

**Issue by mthuurne** [Instagram/MonkeyType#140]
It can be useful to rewrite type annotations in a module even when no additional type information is available. For example, this can be used to convert Python 3.5 `# type:` comments into Python 3.6 annotations.

The impact on the code is rather small: when no stubs are found, just create an empty `ModuleStub` object instead of calling `complain_about_no_traces()` and exiting.

I can clean up my hack by adding a command line option to toggle this behavior and do a proper pull request if you think this would be a useful feature for other users as well.

**Comment by carljm** [comment]
Hi @mthuurne! Thanks for the suggestion, and your patience waiting for a reply.

The functionality you describe is already well provided by the https://github.com/ambv/retype package; in fact MonkeyType just shells out to this package to apply types from stubs. So I don't think it makes sense to turn MonkeyType into a no-op pass-through to retype, when you could just run retype directly.

If you have an idea of where to put a note about this in the docs that might have helped you find retype, I'd welcome a PR for that!
