### ISSUE TITLE
option to generate stubs that ignore existing annotations

### ISSUE THREAD

**Issue by carljm** [Instagram/MonkeyType#15]
By default MonkeyType respects existing annotations as the authority, and uses them over annotations inferred from traces when generating stubs. 

For checking correctness of existing annotations against recorded traces, it would be useful to have an option to generate a stub that only considers the traces and ignores existing annotations.

**Comment by carljm** [comment]
Nope, nobody's started work on this that I know of! We were just discussing today how useful it would be, though :) The API should be pretty simple, just a new CLI option like `--ignore-existing-annotations` to `monkeytype stub` command. (It should not be available to `monkeytype apply`; if you ignore existing annotations and try to apply, it'll probably crash with conflicting annotations.)

As far as implementation details, I haven't really looked into it much. If you dive in and have questions, feel free to ask!

**Comment by tyrinwu** [comment]
Thank you so much for the information!! I do feel this would be useful. Will work on it!

**Comment by carljm** [comment]
Fixed with merge of #55
