### ISSUE TITLE
Invalid import when list contains dict

### ISSUE THREAD

**Issue by csernazs** [Instagram/MonkeyType#159]
Given the following code:
```python
def foo(a):
    print(a)

foo([{"a": "b"}])
```
When it gets annotated by monkeytype the following will be the result:
```python
from monkeytype.encoding import DUMMY_NAME
from typing import List
def foo(a: List[DUMMY_NAME]) -> None:
    print(a)

foo([{"a": "b"}])
```

This raises `ImportError` as there's no `DUMMY_NAME` in `monkeytype.encoding`.

I'm using the latest monkeytype which is `MonkeyType==19.11.2`.

**Comment by IaroslavR** [comment]
I can confirm this behavior. Same version
