### ISSUE TITLE
No traces found, sqlite database empty?

### ISSUE THREAD

**Issue by dan-stromberg** [Instagram/MonkeyType#166]
Hi folks.

Here's what I'm seeing:

> $ seq 5 | python3 -m monkeytype run mtee.py cat 'head -n 2'
> below cmd output started 2020 Tue Mar 10 01:08:12 PM PDT
> Creating 2 pipes
> popening command 0: cat
> popening command 1: head -n 2
> 1
> 2
> 3
> 4
> 5
> 1
> 2
> above cmd output done    2020 Tue Mar 10 01:08:12 PM PDT
> dstromberg@dstromberg-inspiron-5570:~/src/home-svn/mtee/trunk x86_64-pc-linux-gnu 3789
> 
> $ sqlite3 monkeytype.sqlite3 
> below cmd output started 2020 Tue Mar 10 01:08:28 PM PDT
> SQLite version 3.22.0 2018-01-22 18:45:57
> Enter ".help" for usage hints.
> sqlite> SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;
> monkeytype_call_traces
> sqlite> select * from monkeytype_call_traces;
> sqlite> 
> above cmd output done    2020 Tue Mar 10 01:08:56 PM PDT
> dstromberg@dstromberg-inspiron-5570:~/src/home-svn/mtee/trunk x86_64-pc-linux-gnu 3789
> 
> $ monkeytype stub mtee
> below cmd output started 2020 Tue Mar 10 01:09:08 PM PDT
> No traces found for mtee; did you pass a filename instead of a module name? Maybe try just 'mtee'.
> above cmd output done    2020 Tue Mar 10 01:09:09 PM PDT
> dstromberg@dstromberg-inspiron-5570:~/src/home-svn/mtee/trunk x86_64-pc-linux-gnu 3789

Am I doing something wrong?  I saw https://github.com/Instagram/MonkeyType/issues/64 - but I don't think it's the same problem based on the sqlite database being empty and me passing a module name.

Any suggestions?

BTW, mtee is at http://stromberg.dnsalias.org/~strombrg/mtee.html - in case you want to try this yourself. It's not necessarily in need of type annotation - I'm just using it as a test bed before doing a presentation or two about type annotations that hopefully will include a few slides about MonkeyType.

Thanks!

**Comment by dan-stromberg** [comment]
BTW, I'm using:
$ python3 -m pip freeze | grep -i monkeytype
below cmd output started 2020 Tue Mar 10 01:20:52 PM PDT
MonkeyType==19.11.2

On:
$ python3 --version
below cmd output started 2020 Tue Mar 10 01:21:10 PM PDT
Python 3.6.9
above cmd output done    2020 Tue Mar 10 01:21:10 PM PDT
dstromberg@dstromberg-inspiron-5570:~/src/home-svn/mtee/trunk x86_64-pc-linux-gnu 3789

$ cat /etc/lsb-release 
below cmd output started 2020 Tue Mar 10 01:21:16 PM PDT
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=19.3
DISTRIB_CODENAME=tricia
DISTRIB_DESCRIPTION="Linux Mint 19.3 Tricia"

**Comment by carljm** [comment]
Seems likely #19; MonkeyType can't trace functions in the script you run directly, only library modules imported from that script. Create a bare-bones entry-point script next to `mtee.py` that imports and calls into functions from it, and you should see traces. This is also documented in the MonkeyType docs.

**Comment by dan-stromberg** [comment]
That worked.  Thank you.

I also needed to add an if __name__ == '__main__'
