### ISSUE TITLE
monkeytype stub error

### ISSUE THREAD

**Issue by aabramovrepo** [Instagram/MonkeyType#174]
Hi All,

   I'm having troubles with the very 1st example on README. I have created a module `some/module.py` containing the only function:

```
def add_numbers(a, b):
    return a + b
```

my script file `my_script.py` in the main directory looks like:

```
from some.module import add_numbers

add_numbers(2, 3)

```

thus no main or other functions, just a call of `add_numbers`.

`monkeytype run my_script.py` runs fine

`monkeytype stub some/module` throws the following error: `monkeytype stub: error: argument module_path: some/module does not look like a valid Python import path`. 

Any ideas? My plan is to generate annotations for one of my projects applying `monkeytype` to `test` scripts where calls to all my module functions are located. Would that be possible?

Thanks a lot in advance for your help!

Best,
Alexey

**Comment by pradeep90** [comment]
You want `monkeytype stub some.module`, as per the README.

**Comment by aabramovrepo** [comment]
ah totally overlooked this, thanks, however:

`monkeytype stub some.module`

and

`monkeytype apply some.module`

report `No traces found for module some.module` and no stubs are generated / added to the module file.

**Comment by aabramovrepo** [comment]
solved, sorry for bothering you again! This time did not run `monkeytype run my_script.py` at the very beginning. Thanks for the help, cool stuff!
