### ISSUE TITLE
question about traces

### ISSUE THREAD

**Issue by aabramovrepo** [Instagram/MonkeyType#176]
Dear All,

   is there any way in `monkeytype` to handle the situation in `myscript.py` from README when the function call is inside another function:

```
from some.module import add

def f():
  add(1, 2)
```

in this case I'm getting `No traces found for module some.module`. Is there any workaround? If not, how are you guys traversing all function calls in big projects and let `monkeytype` annotate?

Thanks!

Best,
Alexey

**Comment by aabramovrepo** [comment]
one example for a bit bigger project would help, in my project I wanna parse all functions from the test directory, since all module function calls are in the test scripts.

**Comment by carljm** [comment]
Hi @aabramovrepo , you just need the code to be executed. So in your "inside a function" example, the important thing would be that the script that you run with `monkeytype run` imports and calls the `f` function, so the call to `add` is run under MonkeyType tracing.

For your second question, you should be able to run your test script with `monkeytype run` and then get types from that.

I recommend you give the full MonkeyType documentation (https://monkeytype.readthedocs.io/en/stable/) a careful read, as it covers many more topics than the README.

**Comment by aabramovrepo** [comment]
@carljm thanks a lot for getting back to me, fantastic, I will do!
