### ISSUE TITLE
Enable a timer on running

### ISSUE THREAD

**Issue by SimiCode** [Instagram/MonkeyType#179]
I'm testing a realtime data processing program that never stops running. 
This means monkey type will not ext when started. Is there anyway I can set a timeout when starting the run?

**Comment by carljm** [comment]
As I mentioned in another issue, MonkeyType runs what you tell it to and observes types. It’s up to you to decide what it runs. If you don’t want to trace a program that runs forever, then add a feature to your program to make it stop after some time, or whatever behavior you want, and then ask MonkeyType to trace that. It’s out of scope for MonkeyType to build in support for every possible case (timeouts, run each function once, etc.)
