### ISSUE TITLE
Ability to reduce Union structures

### ISSUE THREAD

**Issue by SimiCode** [Instagram/MonkeyType#180]
I get a lot of `Union[Dict[str, Union[str, List[Dict[str, Union[str, List[Dict[str, str]]]]]]]` when I run my program. Is there a way I can set Monkey type to only recognize the primary data structure and not bother about the contents?
All I want is List, Dict, ... so that I can avoid the unions that are returned because the content of the top level data structure can always change in this case.

**Comment by carljm** [comment]
Yes, you can do this by implementing a custom type rewriter; see the MonkeyType documentation. There’s a default rewriter that replaces nested types with Any if there are more than five types; you could probably reuse that one with a lower threshold even.
