### ISSUE TITLE
Make a command arg to save time on subsequent runs

### ISSUE THREAD

**Issue by SimiCode** [Instagram/MonkeyType#181]
I'm running a data processing program which may re-run the same functions numerous times for the each datapoint in a huge dataset.
After the first run, If I make some modifications to the app and I want MK to re-run it again, Can I save time by telling it to run all functions **atleast once** and then stop.

**Comment by carljm** [comment]
Hi! I’m afraid I don’t think this use case is general enough to deserve support directly in MonkeyType, which would be quite complex to implement. Fundamentally MonkeyType simply traces execution and reports on what types it observed; it is up to you to define what should be executed. If you want to trace something that executes a minimal pass through your complete program, then you should write a script that does exactly that and run it under tracing.
