### ISSUE TITLE
Help: How can I compile my own version?

### ISSUE THREAD

**Issue by SimiCode** [Instagram/MonkeyType#182]
Are there any instructions on how to compile monkeytype locally. I have made lots of personal modifications that may not be PR worthy. 
@carljm

**Comment by carljm** [comment]
MonkeyType doesn’t require any compilation since it’s written in pure Python. You should be able to `setup.py install` your modified copy and use it. For more detailed guidance you should consult a Python packaging tutorial, MonkeyType doesn’t do anything unusual in this regard.

**Comment by SimiCode** [comment]
Thanks a bunch!
