### ISSUE TITLE
Naming of typing.py causing ImportError

### ISSUE THREAD

**Issue by SimiCode** [Instagram/MonkeyType#188]
Trying to run MonkeyType using pure python `python __main__.py` 
causes
```
ImportError: cannot import name 'Any' from partially initialized module 'typing' (most likely due to a circular import) (/Users/U/MonkeyType/monkeytype/typing.py)
```

Why does the `typing.py` file share a similar name to a stdlib module? Could we change its name?

**Comment by carljm** [comment]
Don't run `python` from within the `monkeytype` directory; this puts the wrong directory on `sys.path` and causes this problem. In other words, run `python monkeytype/__main__.py` (or better `python -m monkeytype`, which is the way `__main__.py` is supposed to be used).

I'm not necessarily opposed to renaming `monkeytype/typing.py`, but having all of monkeytype's modules on `sys.path` as both `X` and `monkeytype.X` can cause various subtle problems, so I almost prefer having something that makes this setup fail quickly.

**Comment by SimiCode** [comment]
Just want to not that `python3.7 monkeytype/__main__.py` also fails.

**Comment by carljm** [comment]
Oh, good point, because Python puts the CWD and the directory containing the executed script both on `sys.path`.
