### ISSUE TITLE
Overriden def __new__(cls) on a class generates invalid code

### ISSUE THREAD

**Issue by aabmass** [Instagram/MonkeyType#189]
This is a bit of an edge case. `__new__()` does not require `@classmethod` but it is treated as a classmethod with first param `cls` ([here is the definition in typeshed](https://github.com/python/typeshed/blob/db819480a54f38ed9a607b9829c27ca9de686a5d/stdlib/2and3/builtins.pyi#L57) and [docs](https://docs.python.org/3/reference/datamodel.html#object.__new__)). Monkeytype annotates the param as `cls: Type[Foo]` and the return type as `Foo` which is correct except it is not quoted and so gives a NameError. Also, monkeytype doesn't seem to normally annotate `cls` params.

Repro:
```py
### foo.py
class Foo:
  bar = 'bar'

  def __new__(cls):
    return super().__new__(cls)

  @classmethod
  def some_classmethod(cls):
    return cls.bar

### main.py
from foo import Foo

f = Foo()
f.some_classmethod()
```

```bash
$ monkeytype run -m main
$ monkeytype stub foo
from typing import Type


class Foo:
    @staticmethod
    def __new__(cls: Type[Foo]) -> Foo: ...
    @classmethod
    def some_classmethod(cls) -> str: ...

$ monkeytype apply foo
from typing import Type

class Foo:
  bar = 'bar'

  def __new__(cls: Type[Foo]) -> Foo:
    return super().__new__(cls)

  @classmethod
  def some_classmethod(cls) -> str:
    return cls.bar
```

Now trying to run `main.py` gives `NameError: name 'Foo' is not defined` because of the missing quotes.

**Comment by carljm** [comment]
Thanks for the report. I don't think MonkeyType currently ever quotes type annotations to accommodate forward references. Given that `from __future__ import annotations` is, well, the future, and obviates the need for quoting, I'm not sure we'll invest in adding quoting support. In general it's not really a guarantee that `monkeytype apply` will in every case generate code that runs as-is; the intention is to generate a useful first draft with informative type annotations that can be edited as needed.

We could probably special-case `__new__` to not annotate the first parameter, though I'm not sure how much that matters.

**Comment by aabmass** [comment]
Makes sense, I wasn't aware of the annotations future either. Thanks for the quick reply :)
