### ISSUE TITLE
Running MonkeyType against itself?

### ISSUE THREAD

**Issue by SimiCode** [Instagram/MonkeyType#193]
I can see that the codebase of MonkeyType is type annotated, Big thanks for that.
My question is, How did you achieve this? Did you use Monkeytype to collect its own runtime types? How can I achieve that?

**Comment by carljm** [comment]
We didn't use MonkeyType to annotate itself, we annotated it as we wrote the code. This is what I'd recommend for new code; MonkeyType is mostly intended for annotating legacy untyped code.

That said, in principle I think you _should_ be able to run MonkeyType on itself, e.g. by tracing the execution of the MonkeyType test suite. Never tried it myself, though.
