### ISSUE TITLE
monkeytype destroys default values of keyword-only args

### ISSUE THREAD

**Issue by hauntsaninja** [Instagram/MonkeyType#198]
Here's a repro:
```
(.env) ~/tmp/bug λ cat mod.py   
def foo(a, *, b=5):
    return (a, b)


foo("asdf", b=10)
(.env) ~/tmp/bug λ cat script.py
from mod import *
(.env) ~/tmp/bug λ monkeytype run script.py
(.env) ~/tmp/bug λ monkeytype apply mod    
from typing import Tuple

def foo(a: str, *, b = ...) -> Tuple[str, int]:
    return (a, b)


foo("asdf", b=10)

(.env) ~/tmp/bug λ cat mod.py   
from typing import Tuple

def foo(a: str, *, b = ...) -> Tuple[str, int]:
    return (a, b)


foo("asdf", b=10)
```

**Comment by hauntsaninja** [comment]
The issue is with LibCST, submitted https://github.com/Instagram/LibCST/pull/314

**Comment by carljm** [comment]
Thanks for the report! Going ahead and closing this since the fix is landed in LibCST, and we don't pin a specific LibCST version so there's no further fix needed in MonkeyType besides a new released LibCST.

**Comment by hauntsaninja** [comment]
It looks like MonkeyType does put constraints on LibCST version, given the regression, we should probably update once there's a new LibCST:
https://github.com/Instagram/MonkeyType/blob/686e53981c8ba1e2d59f17cc3aa4af47e1c52ad7/setup.py#L48

**Comment by carljm** [comment]
Oh, I meant we don't set a max version. But you're right, we should update the min version to force the update. Will reopen this to track that.
