### ISSUE TITLE
Steal tests from retype

### ISSUE THREAD

**Issue by hauntsaninja** [Instagram/MonkeyType#199]
#198 felt like a major regression to me. I think one reason is that applying type annotations isn't the focus of LibCST, so test coverage for ApplyTypeAnnotationsVisitor isn't great. To that end, it might be worth stealing the test cases from https://github.com/ambv/retype/blob/master/tests/test_retype.py

I'm not sure how much contributor overlap there is between MonkeyType and LibCST, but I'm filing this issue here, since applying type annotations is definitely important for MonkeyType so there's more of an incentive to improve test coverage. And this is a good first issue, if anyone out there is looking to contribute! :-)

**Comment by carljm** [comment]
Sorry about the regression, that is indeed serious! And thanks for the fix! I'm not sure how much sense it makes to add tests for type application in MonkeyType, since any issues those tests reveal would be issues in LibCST, not in MonkeyType. Definitely makes sense to add more test coverage in LibCST, though!

**Comment by hauntsaninja** [comment]
Oh I agree that tests should be in LibCST! :-) Sorry for being confusing, I filed the issue here because I thought contributors to MonkeyType might be more willing to prioritise ApplyTypeAnnotationsVisitor test coverage than LibCST. I'll re-open the issue on LibCST though!

**Comment by carljm** [comment]
Oh, there's a lot of contributor overlap :) Me and the person who wrote ApplyTypeAnnotationsVisitor in LibCST are really the only MonkeyType contributors. I can't promise we'll prioritize bringing more tests over, but it's definitely a good idea. We would certainly merge a PR that does so :)
