### ISSUE TITLE
quote forward references

### ISSUE THREAD

**Issue by carljm** [Instagram/MonkeyType#2]
Forward references in generated stubs should be quoted.

**Comment by jamessynge** [comment]
This would be great, because otherwise the applied stubs cause a parsing error when loading a module with forward references.

**Comment by carljm** [comment]
On second look, I think this is a retype issue, not a monkeytype issue. Unquoted forward references work fine in stubs, but when we use retype to apply those stubs to a code file, retype should quote them when needed.

Filed https://github.com/ambv/retype/issues/6 and closing this, since it's not actionable in MonkeyType.
