### ISSUE TITLE
This project contains the non-free non-open Facebook BSD+PATENTS license

### ISSUE THREAD

**Issue by gpshead** [Instagram/MonkeyType#20]
Please follow your own practices espoused in https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/

Re-license me maybe?

**Comment by carljm** [comment]
Thanks for the report! Looking into the options here.

**Comment by carljm** [comment]
Relicensed in 56cbc258676a32e8b8c02cf8f569695e22d784f1.
