### ISSUE TITLE
How to deal with embedded C modules

### ISSUE THREAD

**Issue by bstaletic** [Instagram/MonkeyType#208]
My project is meant to be used inside vim. This means that it relies on `import vim` which exists only inside an actual vim instance. The way my tests deal with it is [by assigning a `MagicMock` object into `sys.modules['vim']`](https://github.com/ycm-core/YouCompleteMe/blob/master/python/ycm/tests/test_utils.py#L619).

This worked perfectly fine for the `monkeytype run $(which pytest)` step. However, `monkeytype apply <module name>` and `monkeytype stub <module name>` can't use that sort of a trick as far as I know. Any idea how to work around this?

**Comment by bstaletic** [comment]
More information is probably necessary.

The warnings I get are of the form `WARNING: Failed decoding trace: No module named 'ycm.buffer'`. I get this warning for every module that imports `vim` embedded module. The only one that works is `ycm.unsafe_thread_pool_executor`, which is the only one that doesn't depend on the embedded `vim` module.

Looks like `monkeytype` tries to import the specified module in two places. In [`cli.py`](https://github.com/Instagram/MonkeyType/blob/47f42377419680f518556c7d823540b8852378e9/monkeytype/cli.py#L166) it is used to get to the full path of the file containing the module. I could work around that by adding an additional argument to manually specify the path. The other use of `importlib` is in [`util.py`](https://github.com/Instagram/MonkeyType/blob/47f42377419680f518556c7d823540b8852378e9/monkeytype/util.py#L74).

**Comment by bstaletic** [comment]
I managed to hack around this problem.

```viml
py3 << EOF
import monkeytype.cli
import monkeytype.config
import monkeytype.stubs
class MockCliArgs():
	def __init__(self, m):
		self.module_path = monkeytype.cli.module_path(m)
		self.limit = 2000
		self.verbose = True
		self.config = monkeytype.config.DefaultConfig()
		self.disable_type_rewriting = False
		self.existing_annotation_strategy = monkeytype.stubs.ExistingAnnotationStrategy.REPLICATE
		self.sample_count = False
EOF
py3 import sys
" Repeat the following line for any module you want
py3 monkeytype.cli.apply_stub_handler(MockCliArgs(<module name here>), sys.stdout, sys.stderr)
```

I ran the above from inside vim with cwd being the one containing `monkeytype.sqlite3`.

It did work. I just don't think this should be a way to handle embedded modules.

**Comment by carljm** [comment]
Thanks for the report! I think the `cli_context` config method is intended precisely for this type of case, and it should work to just do your `sys.modules` insertion hack there.

Personally if I were writing your project, I would probably prefer to provide a shim module which does `try: import vim; except ImportError: ...` and explicitly defines a shim version of the functionality provided by the `vim` module if it is not available. Then such `sys.modules` tricks become unnecessary.
