### ISSUE TITLE
Add documentation for running in the context of Django unit tests

### ISSUE THREAD

**Issue by showell** [Instagram/MonkeyType#210]
This is sort of a question disguised as a request for documentation.  I am wondering how to run MonkeyTest in the context of running Django unit tests, where perhaps you would only want the profile call to surround `TestRunner(...).run_tests`.

Or maybe I'm more broadly asking how to turn on instrumentation within code, rather than using the command line.

Apologies in advance if this is already documented somewhere.

This is a cool project!

**Comment by carljm** [comment]
Hi! Thanks for the kind words! Yes, this is documented at https://monkeytype.readthedocs.io/en/stable/tracing.html#trace-context-manager -- let me know if something isn't clear there.

**Comment by showell** [comment]
Ah, that does answer my question perfectly. Thanks for the quick response.
