### ISSUE TITLE
Keyboard binding for next test

### ISSUE THREAD

**Issue by andys8** [Instagram/MonkeyType#214]
It would be awesome if there is a simple keyboard binding (like `<space>` or `<enter>`) to start the next test when on the result page. There is one to "restart" already and a button for the next test. But there's no keyboard shortcut.

Am I missing something?

![image](https://user-images.githubusercontent.com/13085980/97228119-bad69f80-17d6-11eb-99eb-dfc8fa909efe.png)

**Comment by andys8** [comment]
I think "quick tab mode" helps to achieve what I want. I'm still wondering why there is not another keyboard binding, but I'd be fine with using `<tab>` for my use case:

![image](https://user-images.githubusercontent.com/13085980/97228716-9af3ab80-17d7-11eb-800d-104f84276fc2.png)

**Comment by carljm** [comment]
Hi, I'm guessing you were trying to submit an issue for monkeytype.com? This project has nothing to do with that website...

**Comment by andys8** [comment]
Oh, I'm very sorry. Yes. I confused the repository with https://github.com/Miodec/monkeytype
