### ISSUE TITLE
`NewType` generated into invalid type signatures

### ISSUE THREAD

**Issue by folz** [Instagram/MonkeyType#22]
Given

```python
UserId = NewType('UserId', int)

def get_user(self, user_id: UserId) -> 'User':
```

MonkeyType generates

```python
def get_user(
    self,
    user_id: <function NewType.<locals>.new_type at 0x1090a52f0>
) -> 'User': ...
```

which then causes retype to fail with this error message:

```
error: /path/to/module.py: invalid syntax (<unknown>, line 18)
```

This happens even when `--exclude-unparsable-defaults` is passed.

I was able to come up with a solution to this, which I'll submit a PR for. However, it seems hacky to me and I'd appreciate feedback on it.

**Comment by carljm** [comment]
Hmm, yeah, we check for unparsable defaults but not unparsable types; I guess we didn't run into the latter. If we see many more cases like this we might want to expand unparsable-checking to type annotations, too.
