### ISSUE TITLE
Support python 3.9

### ISSUE THREAD

**Issue by zinootje** [Instagram/MonkeyType#221]
Python 3.9 made some changes to typing  (see [https://docs.python.org/3/whatsnew/3.9.html#type-hinting-generics-in-standard-collections](https://docs.python.org/3/whatsnew/3.9.html#type-hinting-generics-in-standard-collections) )

Now generating stubs does not work. It always give errors like the one below for every type:
`WARNING: Failed decoding trace: Attribute specified by 'Dict' in module 'typing' is of type <class 'typing._SpecialGenericAlias'>, not type.
WARNING: Failed decoding trace: Attribute specified by 'List' in module 'typing' is of type <class 'typing._SpecialGenericAlias'>, not type.
`

**Comment by carljm** [comment]
Closing this; Python 3.9 seems to generally work now, and is enabled in CI.
