### ISSUE TITLE
Adding type annotation for class instance

### ISSUE THREAD

**Issue by aravind-spnp** [Instagram/MonkeyType#255]
```python
from django.http import HttpRequest

class Runner:
    def run(self, command: str) -> None:
        eval(command)

def this_is_missed(request: HttpRequest, runner):
    runner.run(request.GET["command"])
```

In the above example is there any possibility to annotate the runner instance automatically as `def check_here(request: HttpRequest, runner: Runner)` using MonkeyType? If there is a possibility how to accomplish that?

**Comment by carljm** [comment]
If the code that you run under MonkeyType tracing passes in a `Runner` instance for the `runner` arg, then it should be annotated as `runner: Runner` by MonkeyType. If that's not happening, I'd need full repro steps in order to debug why not.
