### ISSUE TITLE
Formatter?

### ISSUE THREAD

**Issue by eggplants** [Instagram/MonkeyType#257]
I suggest to introduce [black](https://github.com/psf/black) like [libcst](https://github.com/Instagram/MonkeyType/blob/cef09c6702fbab58e66582f76f2559d6a21e448c/demo/requirements.txt#L2) and [isort](https://github.com/pycqa/isort).

**Comment by eggplants** [comment]
>Not sure how libcst is relevant here

When I thought about what formatter to adopt, I found that libcst uses black and suggested it.

https://github.com/Instagram/MonkeyType/blob/cef09c6702fbab58e66582f76f2559d6a21e448c/demo/requirements.txt#L2

**Comment by carljm** [comment]
Sorry, my reading comprehension fail -- you said "black _like_ libcst", I read it as a "black and libcst and isort" :)
