### ISSUE TITLE
Enhanced features for apply

### ISSUE THREAD

**Issue by gramster** [Instagram/MonkeyType#266]
Note: I have implemented both of these; the question is whether its worth upstreaming my changes.

I am interested in using MonkeyType for creating *and updating* type stubs. There are two features I need that are currently missing that I have in my fork:

- I want to be able to modify `.pyi` files, not just `.py` files, so I added an argument to point to a stub folder, and if that argument is present, after importing a module to find the path the path is adjusted accordingly and the suffix is changed to `.pyi`;
- it seems like MonkeyType assumes that there is a one-to-one correspondence between a module and a source file, and cannot use `apply` on modules that are multi-file folders with an `__init__.py`. My change looks to see if the path that was found during import ends with `__init__.py`, and if so, moves up one level and iterates through all the files in that folder applying changes.

My end goal is to use pyright to generate stubs with return types inferred through code analysis, and then update these with argument types that I get from MonkeyType running over unit test or example code suites (e.g. matplotlib, which has a great set of samples).

Are either of these of interest enough to upstream? All the changes are in `cli.py`.

I'm considering making another change, which is to have the ability to write separate database files for each module. This seems like it could make the stub generation process faster in the case of large numbers of traces. Would that be interesting too?

**Comment by gramster** [comment]
Thanks Carl for clarifying. I guess in the example I tried some code paths were not exercised which is why I got the impression monkeytype wasn't patching those; I've done a few small tests now and and the behavior is as you describe so my recursive change isn't needed. Also, In my experiments I seemed to have some issues with applying the changes to the stubs; I'm really just changing the path be the .pyi file, so don't know why yet, and I haven't dug in deep there; I'll test this out more when I have time (so you could close this issue if you like; if I am satisfied it is working as intended I can open a PR anyway given you said you would consider it). As for the separate database issue, I am going to try your suggestion. I am currently using all the matplotlib samples for creating matplotlib stubs, and the trace is about 50GB, so it could really help in this case.

**Comment by carljm** [comment]
Sounds good! I'll close this umbrella issue but please do open a PR for the applying-to-stubs feature if you get that settled.
