### ISSUE TITLE
Test failures on Python 3.11 due to upstream changes in handling `Tuple[()]` 

### ISSUE THREAD

**Issue by michel-slm** [Instagram/MonkeyType#272]
With Python 3.11 rc2 (on Fedora 37 beta), MonkeyType has several test failures:

[py311.log](https://github.com/Instagram/MonkeyType/files/9649573/py311.log)

**Comment by michel-slm** [comment]
`pytest -vv` output for extra verbosity
[py311vv.log](https://github.com/Instagram/MonkeyType/files/9649589/py311vv.log)

**Comment by michel-slm** [comment]
Looks like the tuple issue is related to this change in cpython: https://github.com/python/cpython/issues/91137

**Comment by carljm** [comment]
Fixed by #279
