### ISSUE TITLE
ImportError: cannot import name '_GenericAlias'

### ISSUE THREAD

**Issue by jkugler** [Instagram/MonkeyType#275]
[See first comment. Seems it's a doc/packaging bug]

I am running Python 3.6 (and all code) in a virtual environment. 

I installed MonkeyType like so:
```
python3.6 -m pipenv run pip install MonkeyType
```
I am invoking pytest like so:
```
python3.6 -m pipenv run monkeytype run pytest -m "not migration_test"
```
I'm getting this traceback:
```
Traceback (most recent call last):
  File "/path/to/venv/bin/monkeytype", line 7, in <module>
    from monkeytype.cli import entry_point_main
  File "/path/to/venv/lib/python3.6/site-packages/monkeytype/__init__.py", line 11, in <module>
    from monkeytype.config import (
  File "/path/to/venv/lib/python3.6/site-packages/monkeytype/config.py", line 20, in <module>
    from monkeytype.db.base import (
  File "/path/to/venv/lib/python3.6/site-packages/monkeytype/db/base.py", line 17, in <module>
    from monkeytype.tracing import CallTrace, CallTraceLogger
  File "/path/to/venv/lib/python3.6/site-packages/monkeytype/tracing.py", line 35, in <module>
    from monkeytype.typing import get_type
  File "/path/to/venv/lib/python3.6/site-packages/monkeytype/typing.py", line 30, in <module>
    from monkeytype.compat import (
  File "/path/to/venv/lib/python3.6/site-packages/monkeytype/compat.py", line 6, in <module>
    from typing import Any, Union, _GenericAlias, ForwardRef  # type: ignore
ImportError: cannot import name '_GenericAlias'
```

This is Python 3.6, on Linux (Ubuntu 20.04).

I am using `typing-extensions = "==4.1.1"` because that is the last version with Python 3.6 support, but I don't think that matters.

```
$ python3.6 -m pipenv run bpython
bpython version 0.22.1 on top of Python 3.6.15 /path/to/venv/bin/python
>>> import typing
>>> typing.__file__
'/usr/lib/python3.6/typing.py'
>>> typing._GenericAlias
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    typing._GenericAlias
AttributeError: module 'typing' has no attribute '_GenericAlias'
```

**Comment by jkugler** [comment]
It seems version 22.2.0 doesn't support Python 3.6 any more, but the docs here: https://github.com/Instagram/MonkeyType and PyPi https://pypi.org/project/MonkeyType/ still says it support 3.6.

**Comment by technicalgrp89** [comment]
seeing same error

**Comment by carljm** [comment]
Sorry I missed the docs references to 3.6, will fix. As [the changelog](https://github.com/Instagram/MonkeyType/blob/main/CHANGES.rst) shows, Python 3.6 support was dropped in MonkeyType major version 22, as Python 3.6 is no longer supported upstream (for almost a full year now). If you are using Python 3.6 you will have to stay pinned to MonkeyType <22.

**Comment by carljm** [comment]
Fixed in https://github.com/Instagram/MonkeyType/commit/e60fe1292e46b28b0d0df463bdf3453627fdf3e0

**Comment by jkugler** [comment]
Thanks for fixing! Yeah, I inherited this project that's still using 3.6. Actively working to move it off 3.6 but haven't gotten there yet.
