### ISSUE TITLE
How to use it without sqlit database?

### ISSUE THREAD

**Issue by FuyuanChen** [Instagram/MonkeyType#283]
I want to use MonkeyType in my project without sqlit. Can you help me? Thanks a lot.

**Comment by sagarbadiyani** [comment]
You can implement the [CallTraceStore](https://monkeytype.readthedocs.io/en/stable/stores.html) interface. Even the SQLite Store implement it, you can follow [its code](https://github.com/Instagram/MonkeyType/blob/63feffb6fc2ee5fc3db319bb98a0c0015e234158/monkeytype/db/sqlite.py#L69) and use it with DB of your choice. All you need to do is implement `make_store`, `add`, `filter`, `list_modules` methods.
