### ISSUE TITLE
rewrite Generator[..., None, None] to Iterator[...]

### ISSUE THREAD

**Issue by carljm** [Instagram/MonkeyType#4]

**Comment by gvanrossum** [comment]
Note that these aren't fully equivalent. Generators have a `close()` method but iterators don't.

**Comment by carljm** [comment]
Hmm, good point. Perhaps that ought to be mentioned at http://mypy.readthedocs.io/en/latest/kinds_of_types.html#generators ?

In practice (at least in our codebase) I find the `close()` method to be rarely/never used, and `Iterator[Foo]` is much nicer on the eyes than `Generator[Foo, None, None]`. So I'd still be inclined to provide this (and probably even enable it by default). But this difference is certainly worth a mention in the docs.

**Comment by gvanrossum** [comment]
Yeah, that's fine. I was just sensitized to the difference by
https://github.com/python/typeshed/issues/1806 (where the key point was
that the docs promised a generator so the close() call should be allowed).
Can you submit a PR for the mypy docs?

**Comment by carljm** [comment]
Done: https://github.com/python/mypy/pull/4424

**Comment by iyanuashiri** [comment]
Hey @carljm, I want to work on this issue. I have gone through the source code and saw a make_generator function. Is my job to change the return value from Generator[..]  to Iterator[..]?

Thank you as you reply

**Comment by carljm** [comment]
Hi @iyanuashiri! Thanks for your interest. We _could_ implement this feature by returning `Iterator[yield_type]` from `make_generator` in the case where `send_type` and `return_type` are both `None`. However, given the above discussion I don't think we should do that, because we want to make it easy for someone to opt-out of the rewriting. So instead we should provide this as a `TypeRewriter` class with a `visit_Generator` method that inspects the `__args__` of the Generator type and rewrites it if the send and return types are `None`. And then add this new `Rewriter` to the default rewriter.

**Comment by iyanuashiri** [comment]
I think I understand what you want me to do. So I should create a class that inherits from `TypeRewriter`, with a `visit_Generator` method that inspects the `__args__` of the Generator type?

**Comment by carljm** [comment]
Yes, that’s right!

**Comment by kevinjqliu** [comment]
> TypeRewriter class with a visit_Generator

@carljm I'm confused by the naming convention. Wouldn't we want to name the new method something like rewrite_Generator because the rewrite method in TypeRewriter class will delegate to getattr(typ, '__name__', None).

**Comment by carljm** [comment]
@kevinjqliu Yes, you're right, that was just me mis-remembering the API. I meant `rewrite_Generator`, not `visit_Generator`.
