### ISSUE TITLE
question: How to type-checking

### ISSUE THREAD

**Issue by Yensan** [Instagram/MonkeyType#44]
I have searched many pages and read MokeyType's Doc, such as: 

https://engineering.instagram.com/let-your-code-type-hint-itself-introducing-open-source-monkeytype-a855c7284881
http://monkeytype.readthedocs.io/en/latest/faq.html
 But I still don't know how to type-checking in Python. Anyone tell me? Or give a link for documents thanks

**Comment by tyrinwu** [comment]
I tried to rewrite the example in README.rst. See https://github.com/tyrinwu/MonkeyType/blob/master/README.rst
Hope this is helpful

**Comment by Yensan** [comment]
@tyrinwu thank you for answer. I know how to annotation, and MonkeyType can do it aotumaticlly.
But, what is the next? How to type-checking? :confused:

**Comment by tyrinwu** [comment]
@Yensan  I am not sure whether this is what you are looking for. Perhaps you can look into https://pypi.python.org/pypi/PyContracts

**Comment by carljm** [comment]
@yensan We don’t use any runtime type checking like PyContracts, we use static type checking via mypy (mypy.readthedocs.io). I will leave this issue open to remind me to add a mention of that to the documentation.

**Comment by Yensan** [comment]
@carljm  Oh, I see. 
This way is better. Runtime type checking is a bad idea. 
For common team that not all of staff is practised python user, type checking is indispensable. 
I heard Instagram guys use awesome Python fashion, so I come here. Hope you can do more for Python.

**Comment by carljm** [comment]
Mentioned mypy in new motivation section in README in a58d6a5ea72ea66964e402890ef76b9fcb0d89a9
