### ISSUE TITLE
rewrite NoneType to None

### ISSUE THREAD

**Issue by carljm** [Instagram/MonkeyType#5]

**Comment by m1schka** [comment]
not sure if it's related but I also have applied the types and it generated `NoneType` as a parameter, which is unknown to standard python and not getting added to the import (the only option would be to import it from monkeytype but I actually don't want monkeytype imports in my business code).

**Comment by iamrajhans** [comment]
@carljm can i take this one

**Comment by carljm** [comment]
@m1schka Yeah, that's this bug. We have https://github.com/Instagram/MonkeyType/blob/d36c344204eea66aada9f39469f71759d0e68c8f/monkeytype/stubs.py#L327 but it seems it's not effective (at least not in all cases). The correct fix here is that we should never generate `NoneType` at all in an annotation, it should always be translated to `None`.

@iamrajhans Sure, thank you!

**Comment by johnarnold** [comment]
I wrote a test case for this. It happens when types like Optional[str, NoneType] or even more complex occur.
My example:
```python
    def test_union_nonetype_annotation(self):
        """NoneType should always be rendered as None"""
        sig = Signature.from_callable(UpdateSignatureHelper.has_annos)
        sig = update_signature_args(sig, {'a': Dict[str, Dict[str, Union[str, NoneType]]]}, has_self=False,
                                    ignore_existing_annotations=True)
        stub = FunctionStub('test', sig, FunctionKind.MODULE)
        expected = 'def test(a: Dict[str, Dict[str, Union[str, None]]], b) -> int: ...'
        assert stub.render() == expected
```
All the magic happens in render_annotations():
https://github.com/Instagram/MonkeyType/blob/master/monkeytype/stubs.py#L333

I'll submit a PR since this keeps biting me.
