### ISSUE TITLE
`monkeytype stub` runs code/starts application

### ISSUE THREAD

**Issue by NotAFile** [Instagram/MonkeyType#57]
Running `monkeytype stub` or `monkeytype apply` on an module executes that module.

This is probably not easily preventable, but I do consider it unexpected behaviour, so it might be best to mention that in the docs somewhere.

**Comment by carljm** [comment]
Yes, thanks for the report, I think it's mentioned somewhere that it imports your code, but we could make this even clearer.

Note that if you use the recommended `if __name__ == '__main__'` idiom to protect module-level executable code, monkeytype will not trigger that; we just import the module, we don't "run" it (in the sense of executing it as `__main__`).
