### ISSUE TITLE
Adding command line options like --diff

### ISSUE THREAD

**Issue by tyrinwu** [Instagram/MonkeyType#58]
Would you be interested in an option like `git diff` so that users can know the differences between existing annotations and stubs generated only from traces?

This option should only be a sub-option to `stub` I think and can make use of `--ignore-existing-annotations`

Expected output: showing existing annotations and stubs learned only from traces (--ignore-existing-annotations) _alternatively_ **only** for functions that disagree between the twos.

Potential benefits: quickly know where differences are.

**Comment by carljm** [comment]
Yes, I think that'd be a useful and natural thing to build on top of `--ignore-existing-annotations`. I think just `monkeytype stub --diff some.module` would make sense. And I think the most useful output would be literally a diff of the stub generated with ignoring existing annotations and without, e.g. generate the two stubs and use https://docs.python.org/2/library/difflib.html#difflib.Differ to show the difference between them. @mpage does that seem right to you?

**Comment by tyrinwu** [comment]
Will there be cases when one line added some more annotation and thus added one more line and push the output behind it backward by one line? (While in the ignore-existing-annotation counterpart, it does not add one more line.)

If this is the case, it will possibly make using [difflib](https://docs.python.org/2/library/difflib.html#difflib.Differ) produces mismatches between lines?

**Comment by carljm** [comment]
@tyrinwu I'm not totally sure I understand the situation you're suggesting, but a) I don't think we wrap long lines in stub output, so I'm not sure how adding an annotation would bump things down a line, and b) difflib is a smart contextual differ, it's not like the entire diff would be thrown off by a one-line difference near the top.

**Comment by mpage** [comment]
@carljm - What you're suggesting sounds great.

**Comment by tyrinwu** [comment]
@carljm Thanks for these comments. You did understand what I was thinking and it is good to know about difflib is contextual.

**Comment by mpage** [comment]
Fixed by #59
