### ISSUE TITLE
No traces found error

### ISSUE THREAD

**Issue by obeavers** [Instagram/MonkeyType#64]
Hey guys,

Excited to get this working, but can't seem to get this to find any traces.

The project in question has nothing to do with Django/webdev -- it is a library of numerically oriented classes and their calculations.

I haven't set a config, and am running this from CMD on a private package. The only "scripts" in the package are tests found as tests/[test].py

I'll try:

`monkeytype run tests/[test].py`

then

`monkeytype stub tests/[test].py`

or 

`monkeytype stub [libraryfile].py`

And all I seem to ever get in return is No traces found.

Am I doing something wrong here? Are there certain assumptions regarding package setup that I'm missing?

Thanks.

**Comment by carljm** [comment]
The name passed to `monkeytype stub` is a module name, not a file name. So it should be `monkeytype stub libraryfile` not `monkeytype stub libraryfile.py`.

I think we could probably detect this situation and give a more useful error. Filed #65.
