### ISSUE TITLE
Useful error message if somebody passes a filename instead of module name to stub/apply

### ISSUE THREAD

**Issue by carljm** [Instagram/MonkeyType#65]
We should be able to detect this with a heuristic like "no traces found and os.path.exists(...)"

Shouldn't just use a naive `endswith('.py')`, it's perfectly valid to have a package or module named `py`.

**Comment by carljm** [comment]
#37 partially implemented this, but since it looks for `os.pathsep`, it doesn't cover the case where someone has a top-level module and just does `monkeytype stub mymodule.py`. So it could still be improved somewhat by doing the `os.path.exists` check in case of no traces found.

**Comment by piperchester** [comment]
It looks like this is in progress by @iamrajhans ?
