### ISSUE TITLE
report number of samples

### ISSUE THREAD

**Issue by carljm** [Instagram/MonkeyType#7]
Report the number of samples that were used to generate a method's stub. This will help gauge confidence in the results.

**Comment by tyrinwu** [comment]
I am interested in this. Could you elaborate a bit on this issue? It seems that there is currently a function `sample_rate` that is not implemented. 

    def sample_rate(self) -> Optional[int]:
        """Return the sample rate for call tracing.
        By default, all calls will be traced. If an integer sample rate of N is
        set, 1/N calls will be traced.
        """
        return None

Is this issue about that? What does a sample mean? Thanks for the intro!

**Comment by carljm** [comment]
The `sample_rate` function is the fallback implementation of a config method that the user of MonkeyType can supply an alternate implementation for. Its purpose is described in the documentation: it allows recording traces from only a sample of the function calls executed, rather than all of them. It's not directly related to this issue.

The idea with this issue is to provide an option to `monkeytype stub` and `monkeytype apply` (maybe `--sample-count`) that would print (to stderr, so as not to interfere with stub output on stdout) something like "Annotation for some.module:somefunc based on 324 call traces." for each function/method annotated. The idea is that this allows you to see which functions were annotated based on very few traces (and thus the annotation might be less reliable).

**Comment by tyrinwu** [comment]
Thank you!! Work on it now.

**Comment by carljm** [comment]
Fixed with merge of #50. Thanks @tyrinwu!

**Comment by tyrinwu** [comment]
@carljm  Pleasure :P
