### ISSUE TITLE
Error: Invalid value for "src": Path "xxx" does not exist.

### ISSUE THREAD

**Issue by misakichan** [Instagram/MonkeyType#77]
My environment：
- Mac OS 10.13.3
- Python 3.6.1
- MonkeyType 18.2.0

Because my scripts directory path contains Spaces.
e.g:`/Users/XXX/Library/Mobile\ Documents/com~apple~CloudDocs/Desktop/pythons/
`
PS:I use apple's iCloud for mac.

When I use `monkeytype apply xxx`，
There will be` Error: Invalid value for "src": Path "Documents/com~apple~CloudDocs/Desktop/pythons" does not exist.`

**Comment by mpage** [comment]
Thanks for the report! Does `monkeytype stub` work for you?

**Comment by misakichan** [comment]
yes. it is work
