### ISSUE TITLE
Option to monkeytype installed packages.

### ISSUE THREAD

**Issue by BoPeng** [Instagram/MonkeyType#82]
For various reasons, my unittest tests against installed packages and it took me a while to figure out why `monkeytype` does not record any type information. I ended up writing the following `monkeytype_config.py`

```
from types import CodeType
from monkeytype.tracing import CodeFilter
from monkeytype.config import DefaultConfig, default_code_filter

class MyConfig(DefaultConfig):

    def code_filter(self) -> CodeFilter:
        def my_code_filter(code: CodeType) -> bool:
            return 'mypackage' in code.co_filename or default_code_filter(code)
        return my_code_filter

CONFIG = MyConfig()
```
where `mypackage` is a hard-coded name for my pakcage. This works, but it is inconvenient when I try to trace different packages, so I am wondering if MonkeyType can provide a command line option to allow tracing certain packages in `site_packages`.

**Comment by BoPeng** [comment]
I cannot really comment on if this is a "corner case" because all my python packages, especially those involve C/C++ extensions are tested after they are installed to site-packages. I do understand your argument but I would appreciate it if you could document this behavior (ignore site-package) more clearly.

**Comment by carljm** [comment]
Sorry for the delay in getting back to this! I think the behavior of the default code filter is already pretty well documented at https://monkeytype.readthedocs.io/en/stable/configuration.html#monkeytype.config.DefaultConfig.code_filter and https://monkeytype.readthedocs.io/en/stable/tracing.html#deciding-which-calls-to-trace -- I also just added an FAQ entry in 97bb12e6154b2bbe89afcee87cfa3ace995ba690. If there's somewhere else in the documentation you think it ought to be mentioned, let me know!
