### ISSUE TITLE
Can't apply stubs

### ISSUE THREAD

**Issue by alok** [Instagram/MonkeyType#91]
I run monkeytype with the command `monkeytype run /usr/local/bin/luigi --module $modulename $taskname) $flags` and gather some traces. `monkeytype list-modules` gives a nonempty list.

But running `monkeytype apply src.data.cashflow_data_utils` (the module name given by `list-modules`) gives this error:

```
ERROR: Failed decoding trace: No module named 'src.data.cashflow_data_utils'                            
ERROR: Failed decoding trace: No module named 'src.data.cashflow_data_utils'                            
ERROR: Failed decoding trace: No module named 'src.data.cashflow_data_utils'                            
ERROR: Failed decoding trace: No module named 'src.data.cashflow_data_utils'                            
ERROR: Failed decoding trace: No module named 'src.data.cashflow_data_utils'
No traces found for module src.data.cashflow_data_utils
```

**Comment by carljm** [comment]
Is the module `src.data.cashflow_data_utils` importable from the context where you are running `monkeytype apply`? E.g. can you run `python -c 'import src.data.cashflow_data_utils'` from that same shell and current-working-directory successfully? I would guess not; that's the issue you need to resolve, and then `monkeytype apply` should work. It needs to be able to import your code.

Comment if you are able to run `python -c 'import src.data.cashflow_data_utils'` without error, but `monkeytype apply` still fails, and we can reopen to investigate.

**Comment by alok** [comment]
D'oh!
