### ISSUE TITLE
Readme example doesn't work with floats ?

### ISSUE THREAD

**Issue by baatout** [Instagram/MonkeyType#94]
Hi. I'm testing the readme example but with floats instead of ints:
```
def add(a, b):
    return a + b
```
and 
```
from some.module import add

add(1.0, 2.0)
```
then
```
$ monkeytype run myscript.py
$ monkeytype stub some.module
```
results in:
```
def add(a: int, b: int) -> float: ...
```
Shouldn't be  `def add(a: float, b: float) -> float: ...` instead ? Maybe I am missing something ?

---
Using a `Python 3.6.5` venv created with `$ Python3.6 -m venv venv`
Monkeytype version: `MonkeyType==18.5.1`

**Comment by carljm** [comment]
I'm not able to reproduce this behavior, with the same version of MonkeyType and Python. Can you ensure that you `rm monkeytype.sqlite3` for a clean slate, and try again?

**Comment by baatout** [comment]
I did something stupid. I already had type annotations in `adder` `def add(a: int, b: int) -> float` and I forgot to put `--ignore-existing-annotations`

Kill me please.
