### ISSUE TITLE
'monkeytype': command not found

### ISSUE THREAD

**Issue by AyushExel** [Instagram/MonkeyType#98]
I have installed monkeytype using pip package manager using the following command:
`pip3 install monkeytype`
When I try to run monkeytype on a test file, I get an error:
`monkeytype run test.py` 
` 'monkeytype': command not found' `

**Comment by carljm** [comment]
Monkeytype is just using the standard setuptools `console_scripts` entry point, so this seems to point to an issue in your python installation (e.g. that the `bin` directory of the Python installation where `pip3` installs to is not on your shell `PATH`, or something).  What are your values for `which pip3` and `echo $PATH`?

**Comment by carljm** [comment]
We should add a `__main__.py` in the monkeytype module so you could try `python3 -m monkeytype run test.py` as an alternative to the installed script. Added #99 to track this.

**Comment by carljm** [comment]
In the meantime, I don't think there's anything here to be fixed in MonkeyType. Will reopen if further info suggests that's wrong.

**Comment by swayamraina** [comment]
Hi!
I have added a __main__ file which redirects to the entry point of the monkeytype application. I feel this should be sufficient for fixing the issue. right?
